# Generated by Django 5.0 on 2024-01-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_blog_date_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Text',
            field=models.TextField(max_length=1000),
        ),
    ]
